blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogEntryListView, BlogEntryCreateView, BlogEntryDeleteView, BlogEntryUpdateView
from blog.views import BlogEntryDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogEntryListView.as_view()), name='blog_entry_list'),
    path('create_entry/', BlogEntryCreateView.as_view(), name='create_entry'),
    path('delete_entry/<int:pk>/', BlogEntryDeleteView.as_view(), name='delete_entry'),
    path('update_entry/<int:pk>/', BlogEntryUpdateView.as_view(), name='update_entry'),
    path('entry_detail/<int:pk>/', cache_page(60)(BlogEntryDetailView.as_view()), name='entry_detail'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls')),
    path('user/', include('users.urls')),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import HomeView, ClientCreateView, ClientListView, ClientUpdateView, ClientDeleteView, \
    MailingDetailView, deactivate_mailing
from mailing.views import MailingListView, MailingCreateView, MailingUpdateView, MailingDeleteView

app_name = MailingConfig.name

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('new_recipient/', ClientCreateView.as_view(), name='new_recipient'),
    path('recipients_list/', cache_page(60)(ClientListView.as_view()), name='recipients_list'),
    path('<int:pk>/update_recipient/', ClientUpdateView.as_view(), name='update_recipient'),
    path('<int:pk>/delete_recipient/', ClientDeleteView.as_view(), name='delete_recipient'),
    path('mailing_list/', MailingListView.as_view(), name='mailing_list'),
    path('new_mailing/', MailingCreateView.as_view(), name='new_mailing'),
    path('<int:pk>/update_mailing/', MailingUpdateView.as_view(), name='update_mailing'),
    path('<int:pk>/delete_mailing/', MailingDeleteView.as_view(), name='delete_mailing'),
    path('<int:pk>/mailing_card/', MailingDetailView.as_view(), name='mailing_card'),
    path('<int:pk>/deactivate_mailing/', deactivate_mailing, name='deactivate_mailing'),
]

mailing/models.py
from django.db import models

from users.models import User


class Client(models.Model):
    """Модель для описания клиента рассылки"""

    email = models.EmailField(max_length=60, verbose_name='e-mail')
    name = models.CharField(max_length=150, verbose_name='ФИО')
    comment = models.TextField(null=True, blank=True, verbose_name='Комментарий')

    owner = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, verbose_name='Пользователь')

    def __str__(self):
        return f"{self.name} {self.email}"

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        ordering = ['name']


class Message(models.Model):
    """Модель для сообщения конкретной рассылки"""

    subject = models.CharField(default='No subject', max_length=100, verbose_name='Тема')
    body = models.TextField(null=True, blank=True, verbose_name='Тело письма')

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Mailing(models.Model):
    """
    Модель для описания рассылки, её содержимого и настроек.
    Ключевая модель приложения
    """

    FREQUENCY = (
        ('daily', 'ежедневно'),
        ('weekly', 'еженедельно'),
        ('monthly', 'ежемесячно')
    )

    STATUSES = (
        ('created', 'создана'),
        ('started', 'запущена'),
        ('finished', 'завершена')
    )

    # Расписание рассылок
    SCHEDULE = {
        FREQUENCY[0][0]: 1,
        FREQUENCY[1][0]: 7,
        FREQUENCY[2][0]: 30
    }

    start_time = models.DateTimeField(verbose_name='Время начала')
    end_time = models.DateTimeField(null=True, blank=True, verbose_name='Время окончания')
    frequency = models.CharField(max_length=7, choices=FREQUENCY, verbose_name='Периодичность')
    status = models.CharField(max_length=8, default='created', choices=STATUSES, verbose_name='Статус')
    updated_at = models.DateTimeField(auto_now=True)

    recipients = models.ManyToManyField(Client, blank=True, verbose_name='Получатели')
    message = models.ForeignKey(Message, null=True, blank=True, on_delete=models.SET_NULL, verbose_name='Сообщение')
    owner = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, verbose_name='Пользователь')

    def __str__(self):
        return f'{self.message}: {self.status} ({self.frequency})'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'


class Log(models.Model):
    """
    Модель для описания лога рассылки, создаваемого в момент отправки
    сообщения рассылки конкретному клиенту этой рассылки
    """

    STATUSES = (
        ('successful', 'успешно'),
        ('error', 'ошибка')
    )

    last_try = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время последней попытки')
    status = models.CharField(max_length=10, choices=STATUSES, verbose_name='Статус попытки')
    server_response = models.CharField(null=True, blank=True, max_length=3, verbose_name='Ответ сервера')

    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='Клиент')
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='Рассылка')

    def __str__(self):
        return f'{self.last_try}: {self.server_response}, {self.status}'

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

mailing/views.py
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import QuerySet
from django.forms import inlineformset_factory, Form
from django.http import Http404, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView

from blog.models import BlogEntry
from mailing import services
from mailing.forms import ClientForm, MailingForm, MessageForm
from mailing.models import Client, Message, Log, Mailing


class MailingAndMessageSaveMixin:
    """
    Миксин, который обуславливает основное поведение при создании
    и изменении объекта рассылки (Mailing) вместе с объектом сообщения (Message),
    связанным с рассылкой
    """

    def get_form_kwargs(self) -> dict:
        """
        Получение и передача объекта текущего юзера в словарь
        с аргументами для инициализации формы
        """

        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs) -> dict:
        """
        Получение данных контекста для шаблона.

        Обуславливает отображение формы сообщения вместе с основной формой страницы
        """

        context_data = super().get_context_data(**kwargs)

        if self.request.POST:
            context_data['message_form'] = MessageForm(self.request.POST)
        else:
            if self.object and self.object.message:
                context_data['message_form'] = MessageForm(instance=self.object.message)
            else:
                context_data['message_form'] = MessageForm()
        return context_data

    def form_valid(self, form: Form) -> HttpResponse:
        """
        Обработка действий при валидности формы.

        Обуславливает сохранение объекта и связанного с ним объекта сообщения (Message),
        при условии, что форма валидна, а юзер авторизован.
        Присваивает объекту в качестве владельца (поле owner) текущего юзера
        """

        context_data = self.get_context_data()
        message_form = context_data['message_form']
        self.object = form.save(commit=False)

        if message_form.is_valid() and self.request.user.is_authenticated:
            message = message_form.save()
            self.object.message = message
            self.object.owner = self.request.user
            self.object.save()
            return super().form_valid(form)
        else:
            return self.form_invalid(form)


class OnlyForOwnerOrSuperuserMixin:
    """
    Миксин, ограничивающий демонстрацию страницы объекта для пользователя,
    который не является ни владельцем объекта, ни суперюзером
    """

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user and not self.request.user.is_superuser:
            raise Http404
        return self.object


class HomeView(MailingAndMessageSaveMixin, CreateView):
    """
    Класс-контроллер для отображения домашней страницы.

    Особенность этой домашней страницы в наличии формы создания рассылки
    """

    model = Mailing
    template_name = 'mailing/home.html'
    form_class = MailingForm
    success_url = reverse_lazy('mailing:home')
    extra_context = {'button': 'Создать', }

    def get_context_data(self, **kwargs) -> dict:
        """
        Отвечает за передачу в контекст информации, которая используется
        для построения некоторой статистики пользователя:
        общее количество рассылок, количество активных рассылок, общее количество клиентов.

        Также добавляет 3 случайные статьи блога (BlogEntry) в контекст
        """

        context = super().get_context_data(**kwargs)
        user = self.request.user
        if user.is_authenticated:
            card_info = services.cache_statistic_card(user)
            context.update(card_info)
        context['object_list'] = BlogEntry.objects.order_by('?')[:3]
        return context


class ClientCreateView(LoginRequiredMixin, CreateView):
    """
    Класс-контроллер для создания клиента (Client)
    """

    model = Client
    template_name = 'mailing/recipient_form.html'
    form_class = ClientForm
    success_url = reverse_lazy('mailing:recipients_list')
    extra_context = {
        'title': 'Создать контакт',
        'button': 'Создать',
    }

    def form_valid(self, form: Form) -> HttpResponse:
        """
        Обработка действий при валидности формы.

        Обрабатывает поля ФИО, объединяя их в одно поле name
        """

        last_name = self.request.POST.get('last_name', '').strip()
        first_name = self.request.POST.get('first_name', '').strip()
        father_name = self.request.POST.get('father_name', '').strip()

        full_name = f"{last_name} {first_name} {father_name}".strip().title()

        form.instance.name = full_name

        self.object = form.save()
        self.object.owner = self.request.user

        return super().form_valid(form)


class ClientListView(LoginRequiredMixin, ListView):
    """
    Класс-контроллер для отображения списка клиентов.

    Просмотр доступен только авторизованным пользователям.
    Список клиентов зависит от статуса текущего пользователя:
    обычный юзер может видеть только клиентов, которых он создавал,
    менеджер и суперюзер могут видеть весь перечень клиентов,
    существующий в базе данных
    """

    model = Client
    template_name = 'mailing/recipients_list.html'

    def get_queryset(self) -> QuerySet:
        user = self.request.user
        is_manager = user.groups.filter(name='Managers').exists()
        if user.is_superuser or is_manager:
            queryset = super().get_queryset().all()
        else:
            queryset = super().get_queryset().filter(owner=user)
        return queryset.order_by('name')


class ClientUpdateView(LoginRequiredMixin, OnlyForOwnerOrSuperuserMixin, UpdateView):
    """
    Класс-контроллер для редактирования клиента (Client).

    Доступ к странице есть либо у создателя этого клиента,
    либо у суперюзера
    """

    model = Client
    template_name = 'mailing/recipient_form.html'
    success_url = reverse_lazy('mailing:recipients_list')
    form_class = ClientForm

    def get_context_data(self, **kwargs) -> dict:
        """
        Добавление в контекст конкретного объекта модели Client,
        а также надписи в заголовке и на кнопке
        """

        context_data = super().get_context_data(**kwargs)
        extra_context = {
            'object': Client.objects.get(pk=self.kwargs.get('pk')),
            'title': 'Изменить контакт',
            'button': 'Сохранить',
        }
        return context_data | extra_context

    def form_valid(self, form):
        """
        Обработка действий при валидности формы.

        Обрабатывает поля ФИО, объединяя их в одно поле name
        """

        last_name = self.request.POST.get('last_name', '').strip()
        first_name = self.request.POST.get('first_name', '').strip()
        father_name = self.request.POST.get('father_name', '').strip()

        full_name = f"{last_name} {first_name} {father_name}".strip().title()

        form.instance.name = full_name

        return super().form_valid(form)


class ClientDeleteView(LoginRequiredMixin, OnlyForOwnerOrSuperuserMixin, DeleteView):
    """
    Класс-контроллер для удаления конкретного клиента
    """

    model = Client
    template_name = 'mailing/recipient_delete.html'
    success_url = reverse_lazy('mailing:recipients_list')

    def get_context_data(self, **kwargs) -> dict:
        context_data = super().get_context_data(**kwargs)
        context_data['object'] = Client.objects.get(pk=self.kwargs.get('pk'))
        return context_data


class MailingListView(LoginRequiredMixin, ListView):
    """
    Класс-контроллер для отображения списка рассылок.

    Обычный пользователь может видеть только те рассылки, которые создал сам,
    менеджеры и суперюзеры могут видеть весь существующий список рассылок
    """

    model = Mailing
    template_name = 'mailing/mailing_list.html'

    def get_queryset(self) -> QuerySet:
        user = self.request.user
        is_manager = user.groups.filter(name='Managers').exists()
        if user.is_superuser or is_manager:
            queryset = super().get_queryset().all()
        else:
            queryset = super().get_queryset().filter(owner=user)
        return queryset.order_by('-updated_at')


class MailingCreateView(LoginRequiredMixin, MailingAndMessageSaveMixin, CreateView):
    """
    Класс-контроллер для создания объекта рассылки.

    Доступ к контроллеру есть только у авторизованных пользователей
    """

    model = Mailing
    template_name = 'mailing/mailing_form.html'
    form_class = MailingForm
    extra_context = {'button': 'Создать', 'title': 'Создать рассылку'}
    success_url = reverse_lazy('mailing:mailing_list')


class MailingUpdateView(LoginRequiredMixin, OnlyForOwnerOrSuperuserMixin, MailingAndMessageSaveMixin, UpdateView):
    """
    Класс-контроллер для изменения объекта рассылки.

    Доступ есть только у владельца рассылки (тот, кто создал рассылку), а также
    у суперюзера
    """

    model = Mailing
    template_name = 'mailing/mailing_form.html'
    form_class = MailingForm
    extra_context = {'button': 'Сохранить', 'title': 'Изменить рассылку'}
    success_url = reverse_lazy('mailing:mailing_list')


class MailingDeleteView(LoginRequiredMixin, OnlyForOwnerOrSuperuserMixin, DeleteView):
    """
    Класс-контроллер для удаления объекта рассылки.

    Доступ есть только у владельца рассылки (тот, кто создал рассылку), а также
    у суперюзера
    """

    model = Mailing
    template_name = 'mailing/mailing_delete.html'
    success_url = reverse_lazy('mailing:mailing_list')

    def get_context_data(self, **kwargs) -> dict:

mailing/templates/mailing/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="py-5 text-center">
        <h2>Создать рассылку</h2>
        <p class="lead">Пожалуйста, заполните все обязательные поля рассылки</p>
    </div>

    <div class="row justify-content-center position-relative mt-5">
        <div class="col-md-6">
            <h4 class="mb-3 text-center">Новая рассылка</h4>
            <form class="needs-validation" action="{% url 'mailing:home' %}" method="post" novalidate>
                {% csrf_token %}
                {{ form.as_p }}
                <hr>
                <h5>Сообщение:</h5>
                {{ message_form.as_p }}
                <button class="btn btn-primary btn-lg btn-block" type="submit"> {{ button }}</button>
            </form>
        </div>
        {% if user.is_authenticated %}
        <div class="position-absolute" style="right: -20%; top: 0; width: 25%;">
            <div class="card custom-border mb-3">
                <div class="card-header">Статистика рассылки</div>
                <div class="card-body">
                    <h4 class="card-title">Общая информация:</h4>
                    <p class="card-text">
                        <strong>Всего рассылок:</strong> {{ total_mailings }}<br>
                        <strong>Активных рассылок:</strong> {{ active_mailings }}<br>
                        <strong>Количество контактов:</strong> {{ unique_clients }}
                    </p>
                </div>
            </div>
        </div>
        {% endif %}
    </div>

    <div class="row justify-content-center mt-5">
        <div class="col-md-10">
            {% for object in object_list %}
            <div class="card mb-3">
                <div class="card-header">
                    <h5 class="card-title">{{ object.title }}</h5>
                </div>
                <div class="card-content-wrapper">
                    {% if object.image %}
                    <img src="{{ object.image.url }}" alt="{{ object.title }}" class="card-image">
                    {% endif %}
                    <div class="card-blog-content">
                        <div class="content-container limited-container">
                            <p class="card-text">{{ object.content|linebreaks }}</p>
                        </div>
                    </div>
                </div>
                <div class="info-container clear-float p-3">
                    <span class="text-muted float-left">Дата публикации: {{ object.publication_date|date:"d.m.Y" }}</span>
                    <span class="text-muted float-right">{{ object.views_number }} просмотров</span>
                </div>
                <div class="card-footer">
                    <div class="button-container">
                        <a href="{% url 'blog:entry_detail' object.pk %}" class="btn btn-warning btn-warning-special">Открыть
                            запись</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_card.html
{% extends 'base.html' %}
{% block content %}
<div class="row justify-content-center mt-4">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header text-center">
                <h4>Рассылка <strong>{{ object.message.subject }}</strong></h4>
            </div>

            <div class="card-body">
                <table class="table table-borderless">
                    <tr>
                        <th>Получатели:</th>
                        <td>
                            <div style="max-height: 150px; overflow-y: auto;">
                                <ul>
                                    {% for recipient in object.recipients.all %}
                                    <li>{{ recipient.name }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <th>Начало:</th>
                        <td>{{ object.start_time }}</td>
                    </tr>
                    <tr>
                        <th>Окончание:</th>
                        <td>{{ object.end_time }}</td>
                    </tr>
                    <tr>
                        <th>Периодичность:</th>
                        <td>{{ object.get_frequency_display }}</td>
                    </tr>
                    <tr>
                        <th>Статус:</th>
                        <td>{{ object.get_status_display }}</td>
                    </tr>
                    <tr>
                        <th>Тема:</th>
                        <td>
                            <div class="static-textarea">{{ object.message.subject }}</div>
                        </td>
                    </tr>
                    <tr>
                        <th>Сообщение:</th>
                        <td>
                            <div class="static-textarea">{{ object.message.body|linebreaks }}</div>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="card-footer text-center">
                <a href="{% url 'mailing:mailing_list' %}"
                   class="btn btn-warning btn-warning-special mb-2">Вернуться к списку</a>
                {% if user.is_superuser or is_manager %}
                    {% if object.status != 'finished' %}
                        <a href="{% url 'mailing:deactivate_mailing' object.pk %}" class="btn btn-warning btn-warning-special mb-2">Отключить</a>
                    {% else %}
                        <button class="btn btn-warning btn-warning-special mb-2" disabled>Отключить</button>
                    {% endif %}
                {% endif %}
                {% if user.is_superuser or user == object.owner %}
                    <a href="{% url 'mailing:update_mailing' object.pk %}"
                       class="btn btn-warning btn-warning-special mb-2">Изменить</a>
                    <a href="{% url 'mailing:delete_mailing' object.pk %}"
                       class="btn btn-danger btn-danger-special mb-2">Удалить</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="center-content">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 content-box">
                <h2 class="text-center">Подтвердите удаление</h2>
                <p class="text-center">Вы уверены, что хотите удалить рассылку </p>
                <p class="text-center">
                    "<strong>{{ object.message.subject }}</strong>" ?</p>
                <form method="post" action="" class="text-center mt-4">
                    {% csrf_token %}
                    <div class="d-flex justify-content-center">
                        <button class="btn btn-danger btn-danger-special px-2 mr-2" type="submit">Удалить</button>
                        <a href="{% url 'mailing:mailing_list' %}" class="btn btn-warning btn-warning-special px-2">Отмена</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
      <div class="py-5 text-center">
        <h2>{{ title }}</h2>
        <p class="lead">Пожалуйста, заполните все обязательные поля рассылки</p>
      </div>

<div class="row justify-content-center">
    <div class="col-md-8 order-md-1">
        <h4 class="mb-3 text-center">Рассылка</h4>
        <form class="needs-validation" action="" method="post" novalidate>
            {% csrf_token %}

                {{ form.as_p }}

                <hr>
                <h5>Сообщение:</h5>

                {{ message_form.as_p }}

                <div class="row">
                    <div class="col-md-6">
                        <button class="btn btn-primary btn-lg btn-block" type="submit">{{ button }}</button>
                    </div>
                    <div class="col-md-6">
                        <a href="{% url 'mailing:mailing_list' %}" class="btn btn-warning btn-warning-special btn-lg btn-block">Отмена</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'base.html' %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 order-md-1">
        <h4 class="mb-3 text-center">Рассылки</h4>

        <div class="container mt-5">

            <div class="mb-4">
                <a href="{% url 'mailing:new_mailing' %}" class="btn btn-primary">Создать новую рассылку</a>
            </div>

            {% for object in object_list %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ object.message.subject }}</h5>
                    <p class="card-text"><strong>Периодичность: </strong>{{ object.get_frequency_display }}</p>
                    <p class="card-text text-muted">Дата начала: {{ object.start_time }}</p>
                    <p class="card-text text-muted">Дата окончания: {{ object.end_time }}</p>
                    <p class="card-text"><strong>Статус: </strong>{{ object.get_status_display }}</p>
                    {% if user.is_superuser or is_manager %}
                        <br>
                        <p class="card-text text-muted"><strong>Создан: </strong>{{ object.owner }}</p>
                    {% endif %}

                    {% if user.is_superuser or is_manager %}
                        {% if object.status != 'finished' %}
                            <a href="{% url 'mailing:deactivate_mailing' object.pk %}" class="btn btn-warning btn-warning-special float-right">Отключить</a>
                        {% else %}
                            <button class="btn btn-warning btn-warning-special float-right" disabled>Отключить</button>
                        {% endif %}
                    {% endif %}

                    <a href="{% url 'mailing:mailing_card' object.pk %}" class="btn btn-warning btn-warning-special">Детали</a>
                    {% if user.is_superuser or user == object.owner %}
                        <a href="{% url 'mailing:update_mailing' object.pk %}" class="btn btn-warning btn-warning-special">Изменить</a>
                        <a href="{% url 'mailing:delete_mailing' object.pk %}" class="btn btn-danger btn-danger-special">Удалить</a>
                    {% endif %}
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/recipient_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="center-content">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 content-box">

                <h2 class="text-center">Подтвердите удаление</h2>
                <p class="text-center">Вы уверены, что хотите удалить получателя <br>
                    <strong>{{ object.name }}</strong>?</p>

                <form method="post" action="" class="text-center">
                    {% csrf_token %}
                    <div class="row justify-content-center">
                        <div class="col-auto">
                            <div class="row">
                                <div class="col-6 pr-1">
                                    <button class="btn btn-danger btn-danger-special" type="submit">Удалить</button>
                                </div>
                                <div class="col-6 pl-1">
                                    <a href="{% url 'mailing:recipients_list' %}"
                                       class="btn btn-warning btn-warning-special">Отмена</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/recipient_form.html
{% extends 'base.html' %}
{% load custom_tags %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 order-md-1">
        <h4 class="mb-3 text-center">{{ title }}</h4>

        <div class="col-md-4 mx-auto">
            <form class="needs-validation" action="" method="post">
                {% csrf_token %}

                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="last_name">Фамилия</label>
                        <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Иванов"
                               value="{% if object|last_name %}{{ object|last_name }}{% endif %}"
                               required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="first_name">Имя</label>
                        <input type="text" class="form-control" id="first_name" name="first_name" placeholder="Иван"
                               value="{% if object|first_name %}{{ object|first_name }}{% endif %}"
                               required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="father_name">* Отчество</label>
                        <input type="text" class="form-control" id="father_name" name="father_name"
                               placeholder="Иванович"
                               value="{% if object|father_name %}{{ object|father_name }}{% endif %}">
                    </div>
                </div>

                <div class="mb-3">
                    {{ form.as_p }}

                    <div class="col-md-6">
                        <span class="text-muted">* необязательные поля</span>
                    </div>
                    <br>

                    <div class="row">
                        <div class="col-md-6">
                            <button class="btn btn-primary btn-lg btn-block" type="submit">{{ button }}</button>
                        </div>
                        <div class="col-md-6">
                            <a href="{% url 'mailing:recipients_list' %}"
                               class="btn btn-warning btn-warning-special btn-lg btn-block">Отмена</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}