blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogEntryListView, BlogEntryCreateView, BlogEntryDeleteView, BlogEntryUpdateView
from blog.views import BlogEntryDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogEntryListView.as_view()), name='blog_entry_list'),
    path('create_entry/', BlogEntryCreateView.as_view(), name='create_entry'),
    path('delete_entry/<int:pk>/', BlogEntryDeleteView.as_view(), name='delete_entry'),
    path('update_entry/<int:pk>/', BlogEntryUpdateView.as_view(), name='update_entry'),
    path('entry_detail/<int:pk>/', cache_page(60)(BlogEntryDetailView.as_view()), name='entry_detail'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls')),
    path('user/', include('users.urls')),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/models.py
from django.db import models

from users.models import User


class Client(models.Model):
    """Модель для описания клиента рассылки"""

    email = models.EmailField(max_length=60, verbose_name='e-mail')
    name = models.CharField(max_length=150, verbose_name='ФИО')
    comment = models.TextField(null=True, blank=True, verbose_name='Комментарий')

    owner = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, verbose_name='Пользователь')

    def __str__(self):
        return f"{self.name} {self.email}"

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        ordering = ['name']


class Message(models.Model):
    """Модель для сообщения конкретной рассылки"""

    subject = models.CharField(default='No subject', max_length=100, verbose_name='Тема')
    body = models.TextField(null=True, blank=True, verbose_name='Тело письма')

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Mailing(models.Model):
    """
    Модель для описания рассылки, её содержимого и настроек.
    Ключевая модель приложения
    """

    FREQUENCY = (
        ('daily', 'ежедневно'),
        ('weekly', 'еженедельно'),
        ('monthly', 'ежемесячно')
    )

    STATUSES = (
        ('created', 'создана'),
        ('started', 'запущена'),
        ('finished', 'завершена')
    )

    # Расписание рассылок
    SCHEDULE = {
        FREQUENCY[0][0]: 1,
        FREQUENCY[1][0]: 7,
        FREQUENCY[2][0]: 30
    }

    start_time = models.DateTimeField(verbose_name='Время начала')
    end_time = models.DateTimeField(null=True, blank=True, verbose_name='Время окончания')
    frequency = models.CharField(max_length=7, choices=FREQUENCY, verbose_name='Периодичность')
    status = models.CharField(max_length=8, default='created', choices=STATUSES, verbose_name='Статус')
    updated_at = models.DateTimeField(auto_now=True)

    recipients = models.ManyToManyField(Client, blank=True, verbose_name='Получатели')
    message = models.ForeignKey(Message, null=True, blank=True, on_delete=models.SET_NULL, verbose_name='Сообщение')
    owner = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, verbose_name='Пользователь')

    def __str__(self):
        return f'{self.message}: {self.status} ({self.frequency})'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'


class Log(models.Model):
    """
    Модель для описания лога рассылки, создаваемого в момент отправки
    сообщения рассылки конкретному клиенту этой рассылки
    """

    STATUSES = (
        ('successful', 'успешно'),
        ('error', 'ошибка')
    )

    last_try = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время последней попытки')
    status = models.CharField(max_length=10, choices=STATUSES, verbose_name='Статус попытки')
    server_response = models.CharField(null=True, blank=True, max_length=3, verbose_name='Ответ сервера')

    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='Клиент')
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='Рассылка')

    def __str__(self):
        return f'{self.last_try}: {self.server_response}, {self.status}'

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

templates/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">

    <title>SkyShrimp</title>

    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@1,300&family=Raleway:ital,wght@1,200&display=swap"
          rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet"/>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/form-validation.css' %}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet"/>

</head>
<body class="bg-light">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'mailing:home' %}">
        <img src="/media/shrimp.png" alt="Logo" class="navbar-logo">
    </a>
    <span class="navbar-text">SkyShrimp</span>

    <div class="d-flex flex-nowrap mr-auto">
            <a href="{% url 'blog:blog_entry_list' %}" class="btn btn-outline-secondary mr-2" type="button">Новости</a>
        {% if user.is_authenticated %}
            <a href="{% url 'mailing:recipients_list' %}" class="btn btn-outline-secondary" type="button">Получатели</a>
            <a href="{% url 'mailing:mailing_list' %}" class="btn btn-outline-secondary ml-2" type="button">Рассылки</a>
            {% if user.is_superuser or is_manager %}
                <a href="{% url 'users:users_list' %}" class="btn btn-outline-secondary ml-2" type="button">Пользователи</a>
            {% endif %}
            <a href="{% url 'users:profile' %}" class="btn btn-outline-secondary ml-2" type="button">Профиль</a>
            <a href="{% url 'users:logout' %}" class="btn btn-outline-secondary ml-2" type="button">Выйти</a>
        {% else %}
            <a href="{% url 'users:registration' %}" class="btn btn-outline-secondary" type="button">Регистрация</a>
            <a href="{% url 'users:login' %}" class="btn btn-outline-secondary ml-2" type="button">Вход</a>
        {% endif %}

    </div>
</nav>

{% block content %}
{% endblock %}

<footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy; 2023-{% now 'Y' %} SkyShrimp</p>
</footer>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="{% static 'js/holder.min.js' %}"></script>

</body>
</html>